//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMAS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENEGADE;Initial Catalog=HumanResourceKATH;Integrated Security=True")]
        public string HumanResourceHTHConnectionString {
            get {
                return ((string)(this["HumanResourceHTHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENEGADE;Initial Catalog=HumanResourceKATH;Integrated Security=True")]
        public string HumanResourceMasterConnectionString {
            get {
                return ((string)(this["HumanResourceMasterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENEGADE;Initial Catalog=HumanResourceKATH;Persist Security Info=True" +
            ";User ID=sa")]
        public string HumanResourceAGAConnectionString {
            get {
                return ((string)(this["HumanResourceAGAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENEGADEX;Initial Catalog=HumanResourceKATH;Persist Security Info=Tru" +
            "e;User ID=sa")]
        public string HumanResourceAGAConnectionString1 {
            get {
                return ((string)(this["HumanResourceAGAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENEGADEX;Initial Catalog=HumanResourceMaster;Integrated Security=Tru" +
            "e")]
        public string HumanResourceMasterConnectionString1 {
            get {
                return ((string)(this["HumanResourceMasterConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENEGADEX;Initial Catalog=HumanResourceAGA110821;Integrated Security=" +
            "True")]
        public string HumanResourceAGA110821ConnectionString {
            get {
                return ((string)(this["HumanResourceAGA110821ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENEGADEX;Initial Catalog=HumanResourceAGA;User ID=sa;Password={0}")]
        public string HumanResourceConnectionString {
            get {
                return ((string)(this["HumanResourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RENEGADEX;Initial Catalog=HumanResourceAGA;Integrated Security=True")]
        public string HumanResourceAGAConnectionString2 {
            get {
                return ((string)(this["HumanResourceAGAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Renegadex;Initial Catalog=HumanResourceHTHNew;User ID=sa;Password={0}" +
            "")]
        public string HumanResourceVRHConnectionString {
            get {
                return ((string)(this["HumanResourceVRHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Renegadex;Initial Catalog=HumanResourceHTHNew;User ID=sa;Password={0}" +
            "")]
        public string HumanResource_VRHConnectionString {
            get {
                return ((string)(this["HumanResource_VRHConnectionString"]));
            }
        }
    }
}
